[[docs]]
  name = "Introdução"
  weight = 1
  identifier = "introducao"
  url = "/docs/introducao/"

[[docs]]
  name = "Configurações"
  weight = 2
  identifier = "configuracoes"
  url = "/docs/configuracoes/"

[[docs]]
  name = "Aumentos de Posição"
  weight = 3
  identifier = "contratos"
  url = "/docs/contratos"

[[docs]]
  name = "Filtros"
  weight = 4
  identifier = "filtros"
  url = "/docs/filtros/"

[[docs]]
  name = "Configurações de Saída"
  weight = 5
  identifier = "saida"
  url = "/docs/saida"

[[docs]]
  name = "Configurações de Proteção"
  weight = 6
  identifier = "protecao"
  url = "/docs/protecao"

[[docs]]
  name = "Horários"
  weight = 7
  identifier = "horarios"
  url = "/docs/horarios"

[[docs]]
  name = "Meta Diária"
  weight = 8
  identifier = "meta"
  url = "/docs/meta/diaria"

[[docs]]
  name = "Segurança"
  weight = 9
  identifier = "seguranca"
  url = "/docs/seguranca"

[[docs]]
  name = "Configurações Visuais"
  weight = 10
  identifier = "configuracoes_visuais"
  url = "/docs/configuracoes/visuais"